version: '3.9'

networks:
  seec-network:
    name: seec

services:
  postgres:
    container_name: chamado
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: chamados
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5433:5432
    networks:
      - seec-network
      
  backendchamado:
    container_name: backend-chamado
    build:
      context: .
      dockerfile: Dockerfile
    image: backend_chamado
    restart: always
    ports:
      - 3032:3032
    depends_on:
      - postgres
    networks:
      - seec-network
 
  pgadmin:
    container_name: pgadmin_chamado
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "gpg@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "Gpd-sistemas"
    restart: always
    ports:
      - 5050:80
    depends_on:
      - postgres
    networks:
      - seec-network




 
